[project]
name = "unicode_age"
version = "15.0.0"
readme = "README.md"

[project.optional-dependencies]
dev = ["pytest", "twine"]

[build-system]
requires = ["setuptools", "wheel", "Cython"]
build-backend = "setuptools.build_meta"
