name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        run: |
          python3 -m pip install .[dev]
          python3 -m pytest
          python3 -m build .

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.whl
